// ==UserScript==
// @name        no_kyoko
// @namespace   http://FGtatsuro.com
// @description No Kyoko, A Life!(Not 'No Life!')
// @version     1
// @include http://kyoko-np.net/*
// @require http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js
// ==/UserScript==
// Generated by CoffeeScript 1.3.1
(function() {

  $(function() {
    return $("body").empty();
  });

}).call(this);

